---
port: 4000
host: 0.0.0.0
safe: false

# site serving configuration
exclude: [CNAME, README.md, .gitignore, csv_md.py, rsvp_handling.gs,rsvp_plan.md]
# disables post output
permalink: /:title
# Use this if switching to actual posts.
# permalink: /archive/:title
lsi: false
timezone: null


title: 'Sarah and Kirk'
description: "The website for Sarah and Kirk's wedding"
favicon: "img/favicon-diamond.ico"

collections:
  inserts:
    output: true
    permalink: /:name
  rsvp:
    output: true
    permalink: /:collection/:name

colors:
    fullblack: '#000'
    black: '#000'
    fullwhite: '#fff'
    white: '#fff'
    cranberry: '#891b36'
    berry: '#891b36' #
    sage: '#5c745f' #
    gold: '#ba8740'
