---
port: 4000
host: 0.0.0.0
safe: false

# site serving configuration
exclude: [CNAME, README.md, .gitignore, csv_md.py, rsvp_handling.gs,rsvp_plan.md]
# disables post output
permalink: /:title
# Use this if switching to actual posts.
# permalink: /archive/:title
lsi: false
timezone: null


title: 'Sarah and Kirk'
description: "The website for Sarah and Kirk's wedding"
favicon: "img/favicon-diamond.ico"

collections:
  rsvp:
    output: true
    permalink: /:collection/:name
  inserts:
    output: true
    permalink: /:name

colors:
    green: '#40b089' # mint leaf
    black: '#2e2e2e'
    blue: '#7da1bf'   # dusk blue
    brown: '#635147'  # umber
    red: '#fa8072'    # salmon
    white: '#fffdda'  # cream
    yellow: '#fada6e' # half royal half mellow
    fullblack: '#000'
    fullwhite: '#fff'
    berry: '#7a082c' #
    peach: '#f9d6e1' #
    sage: '#227752' #
    herbal: '#0a422a'
    gold: '#cc9f1a'
    tan: '#f4e4b2' #
